#!bin/zsh

alias ls="ls -G"

alias vim="nvim"
alias vi="nvim"

# Git

alias gs="git status"
alias gd="git diff"
alias gb="git branch"
alias gl="git log"
alias gcm="git checkout main || git checkout master"

# Bundler

alias be="bundle exec"
alias ber="bundle exec rake"
alias bes="bundle exec rspec"
