#!/bin/zsh

xcode-select --install

install_or_upgrade_homebrew() {
  if hash brew 2>/dev/null; then
    brew upgrade
  else
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew tap homebrew/cask-versions
    brew tap thoughtbot/formulae
    brew tap heroku/brew
  fi
}

install_brew_packages() {
  declare -a packages_to_install=("git"
                                  "asdf"
                                  "postgres"
                                  "heroku"
                                  "rcm"
                                  "redis"
                                  "tree"
                                  "tmux"
                                  "vim"
                                  "the_silver_searcher"
                                  "gh"
                                  "yarn")
  installed_packages=$(brew list --formula)

  for package in "${packages_to_install[@]}"
  do
    if [[ $installed_packages == *"$package"* ]]; then
      echo "$package already installed through homebrew."
    else
      brew install $package
    fi
  done
}

install_brew_cask_packages() {
  declare -a packages_to_install=("1password"
                                  "alacritty"
                                  "basecamp"
                                  "chromedriver"
                                  "firefox"
                                  "firefox-developer-edition"
                                  "google-chrome"
                                  "ngrok"
                                  "postman"
                                  "slack"
                                  "spotify"
                                  "sublime-text"
                                  "tuple"
                                  "visual-studio-code"
                                  "whatsapp")
  installed_packages=$(brew list --cask)

  for package in "${packages_to_install[@]}"
  do
    if [[ $installed_packages == *"$package"* ]]; then
      echo "$package already installed through brew cask."
    else
      brew install $package --cask
    fi
  done
}

install_powerline_fonts() {
  git clone https://github.com/powerline/fonts.git --depth=1
  cd fonts
  ./install.sh
  cd ..
  rm -rf fonts
}

install_or_upgrade_homebrew
install_brew_packages
install_brew_cask_packages
install_powerline_fonts

env RCRC=$HOME/dotfiles/rcrc rcup

asdf install

# Setup sublime-text extensions
sublime_location="/Users/$USER/Library/Application Support/Sublime Text 3/Packages/User"
current_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
for filename in $current_dir/sublime-text/*; do
  name=$(basename "$filename")
  ln -i "$filename" "$sublime_location/$name"
done

# Setup vim plugins
source $HOME/.zshrc
update_vim_plugins
